openapi: 3.0.0
info:
  title: Influ AI Suggestions Generation API
  description: API documentation for managing content on Influ AI, including suggestions generation, fetching, updates, and downloads.
  version: "1.0"

paths:
  /suggestions:
    get:
      summary: Fetch User Suggestions (Generations)
      description: Retrieve a paginated list of generated content by the user.
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            description: The maximum number of items to return per page.
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
            description: The starting point for the list of items.
      responses:
        '200':
          description: A list of content items with pagination metadata.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Suggestion'
                  pagination:
                    type: object
                    properties:
                      total_items:
                        type: integer
                        example: 120
                      limit:
                        type: integer
                        example: 10
                      offset:
                        type: integer
                        example: 20
                      has_more:
                        type: boolean
                        example: true
      security:
        - bearerAuth: []

  /suggestions/{id}:
    get:
      summary: Get Content Details
      description: Retrieve detailed information for a specific piece of generated content.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: The unique identifier of the content
      responses:
        '200':
          description: Detailed content information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Suggestion'
      security:
        - bearerAuth: []

  /suggestions/generate:
    post:
      summary: Generate New Suggestion
      description: Create a new piece of content based on selected options, such as "Smart Script," "Custom Script," or "Video."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                suggestion_type:
                  type: string
                  enum: ["smart_script", "custom_script", "video"]
                user_input:
                  type: string
                  description: "Details provided by the user for custom requests"
      responses:
        '202':
          description: Suggestion generation initiated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "submitted"
                  suggestion_id:
                    type: string
                    example: "generated_suggestion_id"
        '429':
          description: Rate limit exceeded.
      security:
        - bearerAuth: []

  /suggestions/{id}/regenerate:
    post:
      summary: Regenerate Suggestion
      description: Initiates a regeneration process for the specified suggestion. This is a non-idempotent operation and may produce a new result with each request.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: The unique identifier of the content
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                user_input:
                  type: string
                  description: "Prompt or new caption"
      responses:
        '202':
          description: Suggestion regeneration started successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "submitted"
        '429':
          description: Rate limit exceeded.
      security:
        - bearerAuth: []

  /suggestions/{id}/feedback:
    post:
      summary: Content Feedback (Thumbs Up/Down)
      description: Allows users to provide feedback on suggestions, such as a thumbs-up or thumbs-down.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: The unique identifier of the content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
                  enum: ["LIKE", "DISLIKE"]
      responses:
        '200':
          description: Feedback submitted successfully.
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Suggestion:
      type: object
      properties:
        id:
          type: string
          example: "suggestion_id"
        type:
          type: string
          enum: ["smart_script", "custom_script", "video"]
          example: "video"
        created_at:
          type: string
          format: date
          example: "2024-04-05"
        status:
          type: string
          enum: ["submitted", "in_progress", "available"]
          example: "available"
        title:
          type: string
          example: "Suggestion title"
        text:
          type: string
          example: "Description of the suggestion"
        media:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: "example_video_1"
              thumbnail_url:
                type: string
                example: "https://link-to-thumbnail.jpg"
              download_url:
                type: string
                example: "https://link-to-video-download.mp4"
